backend:
  name: git-gateway
  repo: deskmisadossite/deskmisados
  branch: main

site_url: https://deskmisadossite.github.io/deskmisados
display_url: https://deskmisadossite.github.io

media_folder: "assets/img/posts"
public_folder: "/deskmisados/assets/img/posts"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "TÃ­tulo", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }
